---
- name: Ensure join commmand file is copied
  become: true
  become_user: kube
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0_777

- name: Ensure join command file is available
  ansible.builtin.stat:
    path: /tmp/kubernetes_join_command
  register: join_command

- name: Ensure node has joined the cluster
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not
  when: join_command.stat.exists
