name: Terraform
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tflint
        run: docker run -v $GITHUB_WORKSPACE/terraform:/data ghcr.io/terraform-linters/tflint
