# This is a basic workflow to help you get started with Actions

name: Terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tflint
        run: |
          cd $GITHUB_WORKSPACE/terraform
          docker run -v $(pwd):/data ghcr.io/terraform-linters/tflint
