# This is a basic workflow to help you get started with Actions

name: Terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install tflint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Runs a set of commands using the runners shell
      - name: Run tflint
        run: |
          cd $GITHUB_WORKSPACE/terraform
          tflint .
