---
- name: Ensure "kube" group is created
  ansible.builtin.group:
    name: kube

- name: Ensure "kube" user is created
  ansible.builtin.user:
    name: kube
    group: kube
    append: true
    createhome: true
    shell: /bin/bash

- name: Ensure "kube" user has sudo permissions
  ansible.builtin.copy:
    dest: /etc/sudoers.d/kubernetes
    content: "kube ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Ensure "kube" user has a SSH authorized key
  ansible.builtin.authorized_key:
    user: kube
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_ed25519.pub

- block:
    - name: Ensure modules for "containerd" can be loaded
      ansible.builtin.copy:
        src: files/containerd.conf
        dest: /etc/modules-load.d/containerd.conf

    - name: Ensure modules for "containerd" are loaded
      ansible.builtin.shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

- block:
    - name: Ensure kernel settings for "containerd" can be applied
      ansible.builtin.copy:
        src: files/99-kubernetes-cri.conf
        dest: /etc/sysctl.d/99-kubernetes-cri.conf

    - name: Ensure kernel settings for "containerd" are applied
      ansible.builtin.command: sudo sysctl --system

- name: Ensure "containerd" is installed
  ansible.builtin.apt:
    name: containerd
    state: latest

- block:
    - name: Ensure "containerd" config dir is created
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: Ensure "containerd" config is created
      ansible.builtin.shell: |
        sudo containerd config default | sudo tee /etc/containerd/config.toml

    - name: Ensure "containerd" service is reloaded
      ansible.builtin.service:
        name: containerd
        state: restarted

- block:
    - name: Ensure GPG key for remote APT source is added
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Ensure remote APT source is added
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes

- name: Ensure packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - kubelet
    - kubeadm
    - kubectl
